### ISSUE TITLE
Invalid colorwallmounted param2 can be generated on homedecor:glowlight_small_cube_14

### ISSUE THREAD

**Issue by debagos** [mt-mods/homedecor_modpack#33] opened 2022-05-05 12:55 UTC
Stack trace:
```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'wielded_light' in callback environment_Step(): ...minetest-5.5.0/bin/../mods/mesecons/mesecons/presets.lua:67: attempt to index local 'dir' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	...minetest-5.5.0/bin/../mods/mesecons/mesecons/presets.lua:67: in function 'get_any_inputrules'
ERROR[Main]: 	...inetest-5.5.0/bin/../mods/mesecons/mesecons/internal.lua:97: in function 'get_any_rules'
ERROR[Main]: 	...etest-5.5.0/bin/../mods/mesecons/mesecons_wires/init.lua:81: in function <...etest-5.5.0/bin/../mods/mesecons/mesecons_wires/init.lua:67>
ERROR[Main]: 	...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:137: in function 'execute'
ERROR[Main]: 	...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:111: in function <...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:73>
ERROR[Main]: 	...i/github/minetest-5.5.0/bin/../builtin/game/register.lua:425: in function <...i/github/minetest-5.5.0/bin/../builtin/game/register.lua:409>
```
For more details please see https://github.com/minetest-mods/mesecons/issues/610

**Comment by OgelGames** [comment] 2022-05-06 02:36
The correct place for this issue is homedecor, it's a bug with the node, not unifieddyes.

**Comment by wsor4035** [comment] 2022-05-06 02:37
no, the issue is with unified dyes as it is what allows the node param2 to be changed via crafting or the airbrush

**Comment by wsor4035** [comment] 2022-05-06 02:56
from ogelgames: could be another tool like technics screwdriver. was not able to replicated with the regular one or technics

**Comment by wsor4035** [comment] 2022-05-06 03:00
update, was able to replicate with technics sonic screwdriver, not only did it create the invalid param2, it also broke the coloring of the node

**Comment by wsor4035** [comment] 2023-10-26 21:35
actual issue is the tool in technic, closing this

**Comment by OgelGames** [comment] 2023-10-27 02:59
No, it's not, it's an issue with anything that sets a bad param2. Unless this has been fixed, it should stay open.

**Comment by wsor4035** [comment] 2023-10-27 03:07
> it's an issue with anything that sets a bad param2
thank you for making my point for me
its an issue with the thing that sets the bad param2, the node can do nothing about that

**Comment by wsor4035** [comment] 2023-10-27 03:11
the actual issue has an issue tracking it over on technic: https://github.com/mt-mods/technic/issues/267 this is completely redundant and pointless

**Comment by OgelGames** [comment] 2023-10-27 04:20
Okay, mesecons was patched to fix this crash over a year ago: https://github.com/minetest-mods/mesecons/pull/623

So yeah, this issue can be closed 👍

**Closed by OgelGames** 2023-10-27 04:20 UTC
Labels: bug, testing needed
