### ISSUE TITLE
Mailbox disappearing after placement

### ISSUE THREAD

**Issue by IIIullaIII** [mt-mods/homedecor_modpack#36] opened 2022-06-05 20:57 UTC
Hi Vanessa, we haven't heard for a while :-P, the mailbox has a problem I have to replace it every time because after a while it disappears, as if I'm not mistaken it also happened for the doors.
Regards Ulla

**Comment by S-S-X** [comment] 2022-06-05 21:10
I guess this probably has something to do either with other mods or possibly with lag / dropping packets.

* How long approximately it takes for mailbox to disappear after you placed it?
* Does it disappear every time and never stays or does it sometimes stay?

Additionally these might help to find out more about issue:

* What other mods are installed?
  * Are mods installed from ContentDB or directly from git repositories?

That said I do not have a lot experience with homedecor so I am mostly just guessing. Additional information however will probably be helpful.

**Comment by SwissalpS** [comment] 2022-06-06 01:45
I cannot reproduce. Placed a homedecor:inbox and it stayed for 30 seconds until I dug it up.

**Comment by wsor4035** [comment] 2022-06-06 02:04
can not confirm either, tested to see if unloaded and reloading caused it as well (if a lbm was doing stuff). probably should close in a day if no further comments from the author @IIIullaIII

**Comment by OgelGames** [comment] 2022-06-06 02:36
> Hi Vanessa, we haven't heard for a while :-P

Vanessa retired from Minetest:  [minetest-mods.github.io/issues/116](https://github.com/minetest-mods/minetest-mods.github.io/issues/116)

**Comment by wsor4035** [comment] 2022-06-07 00:32
closing as two members are unable to reproduce, and have waited. will reopen if further information is provided

**Comment by IIIullaIII** [comment] 2022-06-11 13:28
Sorry I've been out on business,
1 the mail box disappears when the player moves away from it
2 always happens
3 yes I have mods from both ContentDB and my mods too
4 my mods don't clash with homedecor and that's been happening since I updated homedecor some time ago
5 this takes place on the "ITALIAN ULLA SERVER" server
6 Thanks for your reply and sorry for the delay again, I thought it was a known problem but I see that it is not, I tested in another world in single player and this does not happen, now I will slowly activate the same mods that are on the server one at a time to find which is the one that contrasts then I'll let you know
7 :-( I didn't know that vanessa had retired

**Comment by S-S-X** [comment] 2022-06-11 14:05
From serverlist: 5.5.0, minetest, v7
<details><summary>Mods (417):</summary>
- 3d_armor
- 3d_armor_ip
- 3d_armor_sfinv
- 3d_armor_stand
- 3d_armor_ui
- 3d_plants
- abriflame
- abriglass
- admin_toys
- advmarkers
- advtrains
- advtrains_attachment_offset_patch
- advtrains_interlocking
- advtrains_line_automation
- advtrains_luaautomation
- advtrains_signals_ks
- advtrains_train_industrial
- advtrains_train_japan
- advtrains_train_steam
- advtrains_train_subway
- advtrains_train_track
- adv_weapons
- agriculture
- airtanks
- amethyst
- anti_lava_area
- anvil
- apartment
- appliances
- areas
- artdeco
- awards
- bakedclay
- bale
- basic_materials
- beacons
- beds
- beverage
- binoculars
- biome_lib
- boards
- boats
- bonemeal
- bones
- boost_cart
- bows
- breadcrumbs
- bridger
- bridges
- bucket
- building_blocks
- bulletin_boards
- butterflies
- cannabis
- carts
- castle_farming
- castle_gates
- castle_lighting
- castle_masonry
- castle_shields
- castle_storage
- castle_tapestries
- castle_weapons
- catchballs
- caverealms
- cement
- character_anim
- chesttools
- climatez
- clothing
- coloredwood
- columnia
- compost
- concrete
- config
- connected_chests
- controls
- crafting_bench
- creative
- creatura
- crops
- cucina_vegana
- currency
- deathlist
- death_messages
- default
- dice
- digilines
- digistuff
- digiterms
- digtron
- diplazer
- display_api
- dlxtrains
- dlxtrains_cargo
- dlxtrains_diesel_locomotives
- dlxtrains_industrial_wagons
- dlxtrains_support_wagons
- doc
- doc_encyclopedia
- doors
- draconis
- drinks
- dungeon_loot
- dye
- elevator
- emerald
- emote
- enchanting
- enhanced
- env_sounds
- epic
- ethereal
- extranodes
- extra_biomes
- facade
- factory_bridges
- fake_fire
- farming
- farming_nextgen
- findbiome
- fire
- fireflies
- fireworkz
- flowers
- flower_cow
- font_api
- font_metro
- food
- food_basic
- food_sweet
- formspecs
- game_commands
- gardens
- give_initial_stuff
- glow
- handle_schematics
- hedges
- hidden_doors
- homedecor_3d_extras
- homedecor_bathroom
- homedecor_bedroom
- homedecor_books
- homedecor_climate_control
- homedecor_clocks
- homedecor_cobweb
- homedecor_common
- homedecor_doors_and_gates
- homedecor_electrical
- homedecor_electronics
- homedecor_exterior
- homedecor_fences
- homedecor_foyer
- homedecor_furniture
- homedecor_furniture_medieval
- homedecor_gastronomy
- homedecor_inbox
- homedecor_kitchen
- homedecor_laundry
- homedecor_lighting
- homedecor_misc
- homedecor_office
- homedecor_pictures_and_paintings
- homedecor_plasmascreen
- homedecor_roofing
- homedecor_seating
- homedecor_tables
- homedecor_trash_cans
- homedecor_wardrobe
- homedecor_windows_and_treatments
- hotbar
- hot_air_balloons
- hud_notify
- hud_timers
- icecream
- ilights
- industrial
- infinity_color
- intllib
- itemframes
- jail
- jukebox
- jumpdrive
- kartcar
- keys
- kitz
- know_where_you_die
- lavalamp
- led_marquee
- letters
- lib_mount
- lightning
- locked_travelnet
- locks
- lucky_block
- magic_compass
- magic_potions
- mahogany
- map
- mappa_treni
- maptools
- markers
- mesecons
- mesecons_alias
- mesecons_blinkyplant
- mesecons_button
- mesecons_carts
- mesecons_commandblock
- mesecons_delayer
- mesecons_detector
- mesecons_doors
- mesecons_extrawires
- mesecons_fpga
- mesecons_gamecompat
- mesecons_gates
- mesecons_hydroturbine
- mesecons_insulated
- mesecons_lamp
- mesecons_lightstone
- mesecons_luacontroller
- mesecons_materials
- mesecons_microcontroller
- mesecons_movestones
- mesecons_mvps
- mesecons_noteblock
- mesecons_pistons
- mesecons_powerplant
- mesecons_pressureplates
- mesecons_random
- mesecons_receiver
- mesecons_solarpanel
- mesecons_stickyblocks
- mesecons_switch
- mesecons_torch
- mesecons_walllever
- mesecons_wires
- meseportals
- mesetec
- metrosigns
- mid_measure
- minecart
- minimap_radar
- minislots_engine
- minislots_golden7s
- minislots_golden7s_deluxe
- minislots_work_files
- minitram_crafting_recipes
- minitram_konstal_105
- minitram_konstal_105_liveries
- mobf_trader
- mobkit
- moblib
- mobs
- mobs_animal
- mobs_humans
- mobs_monster
- mobu
- mob_horse
- modlib
- modutil
- monitoring
- moreblocks
- morebricks
- morelights
- morelights_extras
- morelights_modern
- morelights_vintage
- moreores
- moretrains_basic
- moretrains_gondola
- moretrains_industrial
- moretrains_japan
- moretrains_nightline
- moretrains_steam
- moretrains_vintage
- moretrees
- more_chests
- mtg_craftguide
- multihome
- multi_component_liveries
- mystical_agriculture
- mystical_axes
- mystical_hoe
- mystical_multipurpose_tools
- mystical_pickaxes
- mystical_shovels
- mystical_staffs
- mystical_swords
- mystical_wands
- named_waypoints
- nativevillages
- nixie_tubes
- nodeu
- nyancat
- ontime_clocks
- orbs_of_time
- people
- petz
- pie
- pipeworks
- pkarcs
- pkarcs_doors
- pkarcs_doors3
- player_api
- poi
- ponti
- protector
- ptime
- qa_block
- rangedweapons
- regrow
- regrowing_fruits
- reportlist
- ropes
- ruby
- sailing_kit
- sandwiches
- sapphire
- schemedit
- scifi_nodes
- screwdriver
- sdwalls
- serialize_lib
- servercleaner
- serversay
- server_shop
- sethome
- sfinv
- shields
- shooter
- shooter_crossbow
- shooter_flaregun
- shooter_grenade
- shooter_guns
- shooter_hook
- shooter_rocket
- shooter_turret
- showbones
- signs
- signs_api
- signs_lib
- signs_road
- skinsdb
- smartrenting
- smartshop
- sneak_glitch
- spawn
- sponge
- stairs
- steles
- street_signs
- summer
- technic
- technictrain
- technic_chests
- technic_cnc
- technic_cnc_improve
- technic_grass_clean
- technic_worldgen
- temp_privs
- tnt
- tpr
- train_remote
- travelnet
- treasurer
- treecapitator
- trm_default_example
- troll
- tsm_gift_example
- ts_doors
- ts_workshop
- tubelib2
- tunnelmaker
- unifiedbricks
- unifieddyes
- unified_inventory
- vector_extras
- vessels
- vexcazer
- vexcazer_adpick
- vexcazer_auto_ad_mod
- vexcazer_con
- vexcazer_copy
- vexcazer_default
- vexcazer_extras
- vexcazer_flashlight
- vexcazer_gravity
- vexcazer_invisible
- vexcazer_massive
- vexcazer_nuke
- vexcazer_powergen
- vexcazer_radio
- vexcazer_telepad
- vexcazer_teleport
- vexcazer_travel
- visible_sneak
- visual_line_number_displays
- walls
- warp_potions
- water_life
- weather
- wield3d
- wieldview
- wine
- wool
- worldedit
- worldeditadditions
- worldeditadditions_commands
- worldeditadditions_farwand
- worldedit_brush
- worldedit_commands
- worldedit_gui
- worldedit_hud_helper
- worldedit_shortcommands
- wrench
- xocean
- xpanes
</details>

**Comment by IIIullaIII** [comment] 2022-06-16 18:17
OK I understand the problem,
and yes, it was really "erver cleaner",
it probably has a lot of work since I removed a "cooltree" mod, as it didn't happen before, but why doesn't it happen with anything else but only with a mailbox?

**Comment by BuckarooBanzay** [comment] 2022-06-17 06:07
>  But why doesn't it happen with anything else but only with a mailbox?

I read the `servercleaner` code a bit and i'm not sure how this could happen, in any case:
could you open an issue there (https://github.com/AiTechEye/servercleaner) and also post the contents of the modstorage values from the servercleaner mod (should be in `<worlddir>/modstorage/servercleaner*`) it is possible that the mod registered the mailbox node as unknown node and removes it every time you re-enter the area (lbm)

closing this issue feel free to discuss it further though :+1:

**Closed by BuckarooBanzay** 2022-06-17 06:07 UTC
Labels: question

**Comment by IIIullaIII** [comment] 2022-06-19 13:33
1.098 / 5.000
Risultati della traduzione
Hi BuckarooBanzay,
you're right, now I understand perfectly what happened,
and I can attribute the mistake to my distraction :-),
considering that my server has many mods and blocks registered, I noticed that minetest has a block limit, recently in fact I installed another mod and when starting the server minetest reported errors of missing dependencies to many mods even if the dependencies c 'were and from here I found that the problem came from the excess of registered nodes in fact for this I removed some mods solving that problem, unfortunately when I started the "servercleaner" server it was active and rightly registered a bunch of blocks to delete, restoring the backup I did not clean the servercleaner file in modstorage, in fact I realized now that the giant mushrooms of ethereal disappeared too, XD, Now I directly deleted the file and restarted the server so that it recreated it from scratch, and the problem and definitively solved, I know AITechEye but I will not report this error as it was my mistake, thanks anyway for the help
